import type { Metadata } from "next";
import "./globals.css";
import Provider from "./components/Provider";
import AppBar from "./components/AppBar";
import Footer from "./components/Footer";
import { Toaster } from "react-hot-toast";


export const metadata: Metadata = {
  title: "Bloggey",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <Provider>
          <Toaster />
          <AppBar />
          <main className="flex-1">{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
